### ISSUE TITLE
$name as category in selector popup

### ISSUE THREAD

**Issue by kvde** [JeffDarchuk/SCTokenManager#1]
I always get $name instead of the category name.

![image](https://cloud.githubusercontent.com/assets/1576509/11653018/6e57182a-9d9b-11e5-855f-e6a2bc3174d2.png)

The category name is filled in:

![image](https://cloud.githubusercontent.com/assets/1576509/11653055/b2d9d6b8-9d9b-11e5-9b58-b07d5cf36a62.png)

**Comment by JeffDarchuk** [comment]
Hey Kevin,

Thanks for bringing this to my attention.  The category label field should be a shared field, i'll fix this in a future release.  For now, a workaround would be if you create a version in your version of sitecore's default language.

**Comment by kvde** [comment]
Hey Jeff,

Thanks for your workaround. I have one question. For which item should I create another version? The template of the category? Can I also make it shared?

**Comment by JeffDarchuk** [comment]
Yeah the item that is named "Tokens met vormgeving".  So say your sitecore instance is set up with a default of "en" for language, you would need to add a new version in "en".

If you change the field "Category Label" in template {4645BD90-1874-4456-8338-D7440C20A477} to shared, i believe it would fix the problem.
