### ISSUE TITLE
Problem initializing?

### ISSUE THREAD

**Issue by fuzzyducky** [JeffDarchuk/SCTokenManager#18]
I've pulled down the nuget package and deployed the config and bin's, but don't see the template in /sitecore/templates/System/Token Manager/Root

Error log shows  17252 14:57:18 ERROR TokenManager was unable to initialize
Exception: System.IO.DirectoryNotFoundException
Message: Could not find a part of the path 'C:\PerforceRoot\SitecoreUpgrade\_MainCodeLine\Dist\Website\App_Data\data\packages\TokenManager.TokenManagerPackage.zip'.

Is this missing zip file error relevant to my problem? I am on Sitecore 8.2 initial release.

**Comment by fuzzyducky** [comment]
I found the package and installed it and it works now.
 (https://github.com/JeffDarchuk/SCTokenManager/blob/master/Source/TokenManager/Resources/TokenManagerPackage.zip)

I was following steps on https://jeffdarchuk.com/2016/08/21/getting-started-with-token-manager/ but it didn't mention this.

**Comment by kamsar** [comment]
The package normally installs itself, but if it cannot deploy it from an embedded resource to the Sitecore packages folder for some reason (filesystem permissions?) it will fail to install.

**Comment by JeffDarchuk** [comment]
Kam is right. There's an initialize pipeline process that detects missing parts and installs from the package stored in the binary.  Not sure what would cause what you're seeing

**Comment by JeffDarchuk** [comment]
Wrong button.  Unless you're good with closing this?

**Comment by fuzzyducky** [comment]
Thanks for the response guys. You may be right. If I get conclusive evidence that it isn't permissions, I'll post back.

**Comment by fuzzyducky** [comment]
Oh I see. Our data folder is a virtual directory under App_Data. That path doesn't exist in the filesystem.

**Comment by JeffDarchuk** [comment]
That's a great thing to note in the documentation.  Thank you for sharing!
