### ISSUE TITLE
Allow tokens to live in an arbitrary location

### ISSUE THREAD

**Issue by kamsar** [JeffDarchuk/SCTokenManager#2]
I'd love to be able to use tokens in a multisite solution and place the tokens under each site instead of in the global token location.

This might involve two elements:
* The ability to resolve token collections outside the TokenManager root item. This might be via registering them in a config file - or maybe registering a collection root where items underneath are automatically evaluated for collections.
* The ability to customize how the token collections are resolved to display in the insert dialog (so that we could show only the current site's and global collections). The default implementation could perhaps key off of either a site name or root path that came along with the collection root registration?

**Comment by JeffDarchuk** [comment]
Fixed in TM 2.0.0
