### ISSUE TITLE
Issue with Rendering tokens

### ISSUE THREAD

**Issue by robvtilburg** [JeffDarchuk/SCTokenManager#21]
Hi,

Recently I upgraded the tokenmanager from v1 to v2 when upgrading to sitecore 8.2.
From that point the rendering tokens no longer seem to work.

I've debugged the code and it appears to be caused by the method GetTokenCollection in DefaultTokenKeeperService.

There is a check there that looks as follows:

`var collection = TokenCollections.ContainsKey(collectionName) &&
								 !IsCollectionValid(TokenCollections[collectionName])
					? TokenCollections[collectionName]
					: null;`

My problem there seems to originate from the check !IsCollectionValid(TokenCollections[collectionName]) which was not present in earlier versions. It would appear to me, looking at the naming as well, that the check should be inverted. In my case the rendering tokens start to work as expected again in that case.

Kind regards,
Rob

**Comment by JeffDarchuk** [comment]
Hi Rob,
Thanks for the bug report, a few questions.  What part of the rendering token isn't working?  I attempted to reproduce this locally and was unable to see anything wrong.  Can you include what version of tokenmanger you're using?

**Comment by robvtilburg** [comment]
Hi Jeff,

I was using 2.5.3, also tried to upgrade to the latest nuget package 2.5.5.
For debugging I simply used the master branch and noticed that the method IsCollectionValid returns true in my case and therefore removes the collection, from the list.

Below image shows the result of the conditions:
![image](https://user-images.githubusercontent.com/19473228/28076061-c3c2f2ac-665d-11e7-8f21-42936a750008.png)

And this image shows in my situation the method returns true based on the statistics condition:
![image](https://user-images.githubusercontent.com/19473228/28076138-ff081432-665d-11e7-83de-47ec7fcfbc1e.png)

In the case this happens the rendering token gets replaced with an empty string. 
Pipelines are being called but the token is never matched against the collection in memory because of the RemoveCollection call.

Please let me know if you require more information on this topic.

Kind regards,
Rob

**Comment by JeffDarchuk** [comment]
Yes, i see now what you are talking about.  For some reason i was thinking that ! was there on purpose, but on further inspection you're 100% right, it shouldn't be there.  Thank you for bringing this to my attention, and it's fixed in v 2.5.7

**Comment by robvtilburg** [comment]
Thanks for the quick reply and fix.
We really appreciate the work you guys have put into this library and sharing it of course.
Awesome job!
