### ISSUE TITLE
"DemoAutoToken2" is appearing in content editor

### ISSUE THREAD

**Issue by fuzzyducky** [JeffDarchuk/SCTokenManager#22]
Hi Jeff,

I have an issue where the "DemoAutoToken2" token is appearing in the content editor.  I see it in the decompiled dll from the nuget package (2.5.8), though I don't see a reference to it in your project.

**Comment by JeffDarchuk** [comment]
yep, that's embarassing, I left in the code i was using to test new features.  My apologies for that.  2.5.9 (which i just now pushed) will not have that demo token.

**Comment by fuzzyducky** [comment]
No worries - thanks for the quick response!
