### ISSUE TITLE
How to disable /tokenmanager ui?

### ISSUE THREAD

**Issue by fuzzyducky** [JeffDarchuk/SCTokenManager#24]
Is there a config change to disable the https://<mysitecore>/tokenmanager ui or some other recommended way to remove it from content delivery servers?

**Comment by fuzzyducky** [comment]
I guess our proxy can prevent access, but I am curious if this is a setting too.

**Comment by JeffDarchuk** [comment]
the /tokenmanager ui will be disabled if there is no master database, usually in CD environments there would not be a master database.  Does your CD environment have a master database?

**Comment by fuzzyducky** [comment]
It shouldn't, so good to know. This question was in prep for setting up our CD server. Thanks!
