### ISSUE TITLE
Contenttree.json is pulling everything in on the initial request.

### ISSUE THREAD

**Issue by chadrickman** [JeffDarchuk/SCTokenManager#26]
We're running to a problem where when the user is inserting a token on a content item, the item selector is calling contenttree.json and that initial call is getting every item including the child items and its taking a long time and returning a massive file (5.4MB).

We're looking into setting a lower root item, but I'm wondering if there is a way that contenttree.json could only return the children of the item selected.

**Comment by JeffDarchuk** [comment]
What version of the tokenmanager are you using?  I feel like i fixed this already in a more recent version.

**Comment by chadrickman** [comment]
We're using Token Manager 2.5.7 and Token Manager Core 2.5.7

**Comment by chadrickman** [comment]
I noticed in [ContentTreeNode.cs](https://github.com/JeffDarchuk/SCTokenManager/blob/45583c270a39548404f740696b61c74975a568ed/Source/TokenManager/Handlers/ContentTree/ContentTreeNode.cs#L21) that the constructor is called its never passed a Boolean and it uses the default value. I just quickly glanced through trying to understand.

**Comment by JeffDarchuk** [comment]
I'm working on getting this tested now.  I'll let you know what i come up with.

**Comment by JeffDarchuk** [comment]
hey Chad, well done!  Your analysis was spot on, that was exactly the issue that i embarrassingly never noticed till now.  I've fixed the issue, committed the change, and cut a new release 2.6.1

Updating nuget packages should fix your problem.  I don't believe there is going to be any issue with the tokens you have existing after the upgrade, but it's worth being cautious and checking them before promoting to your live authoring.

Thanks for bringing this to my attention
