### ISSUE TITLE
Allow token collections to contain any token type and have arbitrary hierarchy

### ISSUE THREAD

**Issue by kamsar** [JeffDarchuk/SCTokenManager#3]
In production usage, I think editors would probably wish to group tokens into collections by site section or other logical organization that would not probably map to a single token type per collection. There might also be scenarios where having a hierarchy of "Token Collection Folders" might make sense.

I'd love to see token collections be capable of storing any type of token. You could probably use the `uiGetMasters` pipeline to even enforce those insert options via code so that if people added new token types they could show up automatically.

Depending on the guts it might require refactoring the `getTokenCollection` pipeline into something more like `resolveToken` or something to operate at the item level instead of collection?

**Comment by JeffDarchuk** [comment]
fixed in TM 2.0.0
