### ISSUE TITLE
Item does not render token when pulled by ID

### ISSUE THREAD

**Issue by Ldaco** [JeffDarchuk/SCTokenManager#30]
When using a token in a sectionfooter on a webpage, the renderer correctly replaces the token information with the correct data from the token.  If retrieving the information specifically by the GUID via an itemservice however, the token contents aren't replaced.  Example: `return this.GetItem(query);`

Is there a way to ensure that the tokens are being replaced when specifically getting the item by it's GUID via back end code?

**Comment by JeffDarchuk** [comment]
I believe you should be able to do that like this:

TokenKeeper.CurrentKeeper.ReplaceRTETokens(RenderFieldArgs() { Item = MyItem}, MyItem[MyField]);

**Comment by Ldaco** [comment]
I've got myself to the point in the ItemExport class where I believe I should be getting the values from the item.  Looking at the ReplaceRTETokens method, it looks like it's expecting a "Sitecore.Data.Items.Item", but the item I'm working with is a custom section footer item.  How would you handle that situation?

Here's the code at this point just trying to hard code something to work for a specific item:
```
var newItem = (Sitecore.Data.Items.Item)i;

TokenManager.Management.TokenKeeper.CurrentKeeper.ReplaceRTETokens(new Sitecore.Pipelines.RenderField.RenderFieldArgs() { Item = newItem }, newItem["Content Right"]);
```
but that results in this:

`Unable to cast object of type 'XXX.Web.Sites.YYY.Models.Generated.Concrete.PageComponents.SectionFooter' to type 'Sitecore.Data.Items.Item'.`

**Comment by JeffDarchuk** [comment]
Are you using synthesis?  It looks like synthesis generated code.  Tokenmanager uses Sitecore items.  If i recall correctly there's a property on the synthesis objects to get the base Sitecore item.

**Comment by Ldaco** [comment]
Ah, yes we are using Synthesis. Thanks for the tip, I’ll check it out and report back.

**Comment by Ldaco** [comment]
The inner item off of the IStandardTemplateItem worked for the item and then the next catch was to also add FieldName in the fieldargs.  Works good!  Thanks for the help

```
var tokenArgs = new Sitecore.Pipelines.RenderField.RenderFieldArgs() { Item = i.InnerItem, FieldName = f.Name };
                    var value = TokenManager.Management.TokenKeeper.CurrentKeeper.ReplaceRTETokens(tokenArgs, f.Value);
```
