### ISSUE TITLE
TokenManager deletes all RTE Buttons (and recreates them)

### ISSUE THREAD

**Issue by chaelli** [JeffDarchuk/SCTokenManager#32]
Hi

we noticed, that all RTE Buttons (Insert A Token) are recreated every time sitecore starts (initialize pipeline). This would not be a big issue were these items not serialized and would therefore show as changed when doing a commit.
I looked into the code and the issue seems to be the following:
CleanOldTokenButtons is called with an empty list, as only "AutoToken" buttons are added to the "ValidTokenButtons" (we do not have any AutoTokens).
DefaultTokenKeeperService line number 455 deletes the Buttons, because they are not in ValidTokenButtons.

Therefore it seems that all Buttons that are not connected to a AutoToken are deleted every time Sitecore is initialized.
Do you have an idea how to solve this? 

Cheers
Michael

**Comment by JeffDarchuk** [comment]
The code is designed to delete any removed Autotoken's that define a custom RTE button.  It's supposed to pick up only buttons that are supposed to be controlled by TokenManager and compare them against what's in memory after initializing.

1. What kind of items are being deleted?  According to the code it should only be autotoken buttons and nothing else.
2. When you say you're not using autotokens, does that mean you're exclusively using the Sitecore item based tokens?
3. When you say it's not a big deal, do you mean that no items are erroneously permanently deleted?

**Comment by chaelli** [comment]
1. All "Insert A Token" buttons => how does it differentiate between buttons for AutoTokens and others? I don't see that in code - maybe then I'd find out why they are wrongly deleted (we did update from sitecore 8 recenty.. so we might have wrong templates or something like this)
2. yes
3. they are delete but recreated automatically (probably in AddTokenManagerMainRteButtons)

**Comment by JeffDarchuk** [comment]
Ah, alright that clears it up a bit.  So when initializing it has a system that checks that the required sitecore items are present.  Could you check to see if any of these are missing:

		public const string TokenCollectionStandardValuesId = "{D627C02A-7DD7-4FA6-A1F5-1FBFD869B6F2}";
		public const string TokenFieldId = "{273E8C26-5BF0-4DC1-8430-BDB5C2665853}";
		public const string TokenCollectionCategoryFieldId = "{81941697-38C9-4B03-A045-EB065A690B9E}";

		public const string TokenCollectionCoreTemplateId = "{D31BC00A-F078-4D5D-A93F-CD0E5C850237}";
		public const string TokenTemplateId = "{87BFAA2C-2E2F-42C6-A135-9F2AE7D32807}";

		public const string TokenCollectionFolderTemplateId = "{1068A0B2-91C4-44F2-A7E4-62CE737C595D}";

		public const string TokenTemplateBaseId = "{13632250-8E53-4A36-9E9B-B1DC6452D4C5}";
		public const string TokenCollectionTemplateBaseId = "{4645BD90-1874-4456-8338-D7440C20A477}";

		public const string TokenRootTemplateId = "{D48A879D-2142-4DFB-A773-C8AF686AE779}";
		public const string TokenStripOuterPTagsFieldId = "{01038533-5010-4BD2-A2E5-C08D263CCC7A}";

**Comment by chaelli** [comment]
they all exist (in the master db)

**Comment by JeffDarchuk** [comment]
in that case it definitely seems like a bug.  What version of Tokenmanager are you using?

**Comment by chaelli** [comment]
2.6.6 from the nuget package (TokenManager.Core)

**Comment by JeffDarchuk** [comment]
great!  Thanks, i'll try to find some time to address this and push an update for you.

**Comment by chaelli** [comment]
:thumbsup: - thanks a lot

**Comment by chaelli** [comment]
@JeffDarchuk I created a "solution". As I cannot really distinguish between the buttons that should be deleted and the ones that should not (non autotoken buttons are simply not taken into consideration in the existing code), I solved it by allowing the devs to protect the button items and with that protect them from deletion
