### ISSUE TITLE
SwitchMasterToWeb.config enabled on CD crashes TokenManager

### ISSUE THREAD

**Issue by robhabraken** [JeffDarchuk/SCTokenManager#7]
Hi Jeff,

when I enable the SwitchMasterToWeb.config on the content delivery server, the TokenManager generates a null pointer exception on the initialize of the pipeline. When I then disable the Tokens.config, the site works well. On the content management server everything works fine. And locally I can reproduce the above. Am I missing something in the configuration of the TokenManager?

Regards, Rob

[NullReferenceException: Object reference not set to an instance of an object.]
   TokenManager.Pipelines.Initialize.InitializeTokenManager.RegisterSitecoreTokens() +65
   TokenManager.Pipelines.Initialize.InitializeTokenManager.Process(PipelineArgs args) +49
   (Object , Object[] ) +70
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +483
   Sitecore.Nexus.Web.HttpModule.Application_Start() +226
   Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +672
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +617
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +171
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +418
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +342

[HttpException (0x80004005): Object reference not set to an instance of an object.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +120
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +712

**Comment by JeffDarchuk** [comment]
Hey Rob,  Sorry you're having issues here, you shouldn't need to change the configuration file between the two environments.  My first thoughts would be if the tokenmanager root item is published to the CD database.  Right now the initialize pipeline requires that root to exist, which is something I'm looking to fix in the next version.

**Comment by JeffDarchuk** [comment]
What version of TokenManager do you have installed?

**Comment by robhabraken** [comment]
Hey Jeff, thanks for your quick reply. We are using version TokenManager.1.0.9, installed via NuGet. And I have published the whole database to be sure, but the error still occurs.

**Comment by JeffDarchuk** [comment]
Hmm, sounds like an interesting issue.  The method that it's blowing up on only appears to have one parameter that a null reference error is possible and that's on the initialization of the token keeper service

```
		<pipelines>
			<initialize>
				<processor type="TokenManager.Pipelines.Initialize.InitializeTokenManager, TokenManager" >
					<Tokens type="TokenManager.Management.DefaultTokenKeeperService, TokenManager">
						<!--This changes the appearance of tokens in the rich text editor
						NOTE: when changed the css will be updated when a token is regenerated-->
						<param name="TokenCss">font-style: italic;background-color: #A0FFD9;text-decoration: none;</param>
					</Tokens>
```

Could you make sure that the config file is set up correctly in your CD environment?  Also it might be helpful if i knew your sitecore version so i can try to reproduce your error (i haven't been able to thus far)

**Comment by robhabraken** [comment]
Yeah it for sure is not an obvious issue. We use Sitecore version 8.1 rev. 151003 (Initial Release). The config is the same on CM and CD. If I disable the SwitchMasterToWeb it works on CD as well, with the same Tokens.config. Could send you the whole solution, it's only 350 Mb incl. databases, we've just started developing and there's not much content yet, so it's still rather small.

**Comment by JeffDarchuk** [comment]
If you can find a way to get me the project and databases I would be more than happy to take a look.  What is your preferred way to share a larger file like that?

**Comment by robhabraken** [comment]
If you follow me on Twitter (rhabraken) I'll DM you a link to download it.
