### ISSUE TITLE
Tokenmanager crashes on IE11

### ISSUE THREAD

**Issue by MarkMartis** [JeffDarchuk/SCTokenManager#8]
Dear Jeff,

The tokenmanager crashes in IE11. In the rich text editor when we select a tokenmanager component it prompts to select a datasource. When we have selected the datasource the submit button does not respond and the tokenmanager lightbox does not close and update the token into the editor. 

When clicking the button submit it says:
TypeError: Unable to get property 'className' of undefined or null reference. The tokenmanager also does not close in IE11(x button top right). 

These problems do not occur in firefox/chrome(except for angular errors in console). Our client works in a very strict enviroment with only the possibility to work with IE11. Is there any way we can fix this?

Thank you in advance for your reply.

Kind regards,

Mark Martis

**Comment by JeffDarchuk** [comment]
Hey Mark,

Thanks for bringing this to my attention, I'll address it and update the nuget package this weekend.

**Comment by JeffDarchuk** [comment]
Mark,

pull down v 1.1.1 and give it a whirl.  Let me know if it's working all right for you.

**Comment by MarkMartis** [comment]
Hey JeffDarchuk,

Thanks for your fast reply! Here my case:

new error:
I have pulled this and tested it and now the add issue works correctly except it generated another problem. 

Now the renderings dont work when I add a rendering with IE11. With other browsers this is not the case. It seems that in IE11 the tokenmanager do not have the  [class="token-manager-token" ] attribute. 

This problem only occurs on IE11.

Because of this the tokenmanager does not render the rendering and only shows a clickable blue-highlighted text. 

I hope to have informed you well. Let me know if you have a fix for this!

Kind regards,

Mark

**Comment by JeffDarchuk** [comment]
Hey Mark,

Yes you're right, that's exactly what the problem is.  I'll get it fixed up asap.

**Comment by JeffDarchuk** [comment]
Ok, just pushed up 1.1.2

Give that a try.

**Comment by MarkMartis** [comment]
Hey Jeff, 

I agree! IE has always been everyone's favorite browser and still is after so many years. Microsoft loves to give all developers a little challenge :D. 

Thanks for the fast fix! I will try this out!

**Comment by MarkMartis** [comment]
Hi Jeff,

I have tested it and it works as expected. Now I have to wait for our testers for the final validation. Ill keep you posted!

**Comment by MarkMartis** [comment]
Hey Jeff,

Thanks for your help. It seems everything works just perfect. Keep up the great work!

Best regards,

Mark
