### ISSUE TITLE
Tried to install latest version to Sitecore 7.2 and got error

### ISSUE THREAD

**Issue by crsnt** [JeffDarchuk/SCTokenManager#9]
![image](https://cloud.githubusercontent.com/assets/1879280/19229862/4c0eccfe-8f03-11e6-9b28-e7398824fb21.png)

**Comment by kamsar** [comment]
Looks like maybe a category item is not present? One way or another it's trying to find the links for an item that does not exist.

Try rebuilding your link database, no guarantees that it would fix the issue but it could.
